In [22]:
import numpy as np

li=np.arange(12)
li=li.reshape(3,4)
li.shape
#np.shape(li)
li.shape=(4,3)
li.shape

(4, 3)

In [1]:
# example for Generators
import sys


In [26]:
li = [1,2,3,4]
sli = []
for i in li:
    sli.append(i*i)
sys.getsizeof(sli)

96

In [29]:
sg = (i*i for i in range(1,5))
for i in sg:
    print(i)
#print(i)
sys.getsizeof(sg)

1
4
9
16


120

In [30]:
type(sg)

generator

In [31]:
li =[i for i in range(1,100)]

In [32]:
sys.getsizeof(li)

912

In [37]:
sg = (i for i in range(1,100))


<generator object <genexpr> at 0x000002873AE13A98>

In [34]:
sys.getsizeof(sg)

120

In [35]:
li1=[]
for i in range(1,100):
    li1.append(i)


In [36]:
sys.getsizeof(li1)

912

In [38]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [40]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [8]:
# 50 values between 1 and 10:
print(np.linspace(1, 10))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [10]:
# 10 values between 1 and 10:
print(np.linspace(1, 10, 10))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [11]:
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))

[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [12]:
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))


[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [23]:
B = np.array([ [[111, 112, 113], [121, 122, 123]],
               [[211, 212, 213], [221, 222, 223]],
               [[311, 312, 313], [321, 322, 323]],
               [[411, 412, 413], [421, 422, 423]] ])
print(B.shape)

(4, 2, 3)


In [24]:
# Creating Arrays with Ones, Zeros and Empty
i = np.ones((2,3))
i

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
i = np.ones((3,2),dtype=int)
i

array([[1, 1],
       [1, 1],
       [1, 1]])

In [26]:
z = np.zeros((2,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
z= np.zeros((2,2),dtype=int)
z

array([[0, 0],
       [0, 0]])

In [35]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
# The identity Function
np.identity(3)
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [46]:
# The eye Function

np.eye(5)
np.eye(4,6)
np.eye(4,6,k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [47]:
# 1) Create an arbitrary one dimensional array called "v".
a = np.array([3,8,12,18,7,11,30])
a

array([ 3,  8, 12, 18,  7, 11, 30])

In [56]:
# 2) Create a new array which consists of the odd indices of previously created array "v".
odd_elements = a[1::2]
odd_elements

array([ 8, 18, 11])

In [58]:
# 5) Create a two dimensional array called "m".
m = np.array([ [11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
m

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [67]:
l=[1,2,3,4,5]
l=np.array(l)
l+2
l*2
l**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [68]:
v = np.random.randint(0,100,1000)
%timeit v+1

2.06 µs ± 39.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [69]:
%timeit [i+2 for i in v]

310 µs ± 2.84 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [75]:
# addion two arrays
A=np.arange(9).reshape(3,3)
A
B=np.identity(3)
A,B,A+B


(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]), array([[1., 1., 2.],
        [3., 5., 5.],
        [6., 7., 9.]]))

In [76]:
A*B # Wrong procedure for multiplications


array([[0., 0., 0.],
       [0., 4., 0.],
       [0., 0., 8.]])

In [77]:
np.dot(A,B)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [78]:
A==B

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [79]:
print(np.array_equal(A, B))
print(np.array_equal(A, A))

False
True


In [2]:
# Exam Task1
def printCountStar(n):
    sm = 0
    if n==1:
        return 1

    for j in range(1,n+1):
        if j==1:
            sm+=1
        else:
            sm+=(j-1)*5
    return sm      
t = int(input())

for i in range(t):
    n = int(input())
    print(printCountStar(n))


2
4
31
6
76


In [33]:
# Exam Task2
"""
jawed doury yash home
eagle eagle oh house elated
dongle excited
"""
t = int(input())
for i in range(t):
    words = input().split()
    #print(words)
    if len(words)==1:
        print("Valid")
    #print(len(words),len(set(words)))
    elif(len(words)!=len(set(words))):
        print("InValid")
    else:
        falg=0
        for j in range(len(words)-1):
            if(words[j][-1] == words[j+1][0]):
                flag=1
            else:
                flag=0
                break
        if flag==0:
            print("invalid")
        else:
            print("valid")

1
eagle eagle oh house elated
InValid


In [17]:
len(set(['eagle','eagle','oh','house','elated'])),len(['eagle','eagle','oh','house','elated'])

(4, 5)